# Generated by Django 4.2.1 on 2023-06-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremarks', '0002_alter_picks_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picks',
            name='date',
        ),
        migrations.AddField(
            model_name='picks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
