# Generated by Django 4.2.1 on 2023-06-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremarks', '0003_remove_picks_date_picks_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
