# Generated by Django 4.2.1 on 2023-06-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremarks', '0004_employee_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='picks',
        ),
        migrations.RemoveField(
            model_name='picks',
            name='created_at',
        ),
        migrations.AddField(
            model_name='picks',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='picks',
            name='employees',
            field=models.ManyToManyField(to='coremarks.employee'),
        ),
    ]
