# Generated by Django 4.2.1 on 2023-06-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coremarks', '0006_alter_picks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_picked', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremarks.day')),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='items_picked',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='line',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='number_of_picks',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Picks',
        ),
        migrations.AddField(
            model_name='employeeday',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremarks.employee'),
        ),
        migrations.AddField(
            model_name='day',
            name='employees',
            field=models.ManyToManyField(through='coremarks.EmployeeDay', to='coremarks.employee'),
        ),
    ]
